MOUSEPAD_LAYOUT = [
    {
        "key":"",
        "x":0,
        "y":0,
        "width":8,
        "height":40
    },
    {
        "key":"",
        "x":0,
        "y":40,
        "width":8,
        "height":40
    },
    {
        "key":"",
        "x":0,
        "y":80,
        "width":8,
        "height":40
    },
    {
        "key":"",
        "x":0,
        "y":120,
        "width":8,
        "height":40
    },
    {
        "key":"",
        "x":0,
        "y":160,
        "width":40,
        "height":8
    },
    {
        "key":"",
        "x":40,
        "y":160,
        "width":40,
        "height":8
    },
    {
        "key":"",
        "x":80,
        "y":160,
        "width":40,
        "height":8
    },
    {
        "key":"",
        "x":120,
        "y":160,
        "width":40,
        "height":8
    },
    {
        "key":"",
        "x":160,
        "y":160,
        "width":40,
        "height":8
    },
    {
        "key":"",
        "x":200,
        "y":160,
        "width":40,
        "height":8
    },
    {
        "key":"",
        "x":240,
        "y":160,
        "width":40,
        "height":8
    },
    {
        "key":"",
        "x":280,
        "y":160,
        "width":40,
        "height":8
    },
    {
        "key":"",
        "x":310,
        "y":120,
        "width":8,
        "height":40
    },
    {
        "key":"",
        "x":310,
        "y":80,
        "width":8,
        "height":40
    },
    {
        "key":"",
        "x":310,
        "y":40,
        "width":8,
        "height":40
    },
    {
        "key":"",
        "x":310,
        "y":0,
        "width":8,
        "height":40
    },
]

MOUSEPAD_LAYOUT_WIDTH = 330;
MOUSEPAD_LAYOUT_HEIGHT = 180;