MOUSE_LAYOUT = [
    {
        "key":"Main",
        "x":20,
        "y":30,
        "width":30,
        "height":30
    },
    {
        "key":"Scrwhl",
        "x":25,
        "y":0,
        "width":15,
        "height":25
    },
    {
        "key":"",
        "x":0,
        "y":0,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":0,
        "y":15,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":0,
        "y":30,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":0,
        "y":45,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":0,
        "y":60,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":0,
        "y":75,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":0,
        "y":90,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":40,
        "y":0,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":40,
        "y":15,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":40,
        "y":30,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":40,
        "y":45,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":40,
        "y":60,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":40,
        "y":75,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":40,
        "y":90,
        "width":8,
        "height":15
    },
];