MOUSE_LAYOUT = [
    {
        "key":"LOGO",
        "x":23,
        "y":70,
        "width":30,
        "height":30
    },
    {
        "key":"SCROLL",
        "x":23,
        "y":20,
        "width":30,
        "height":30
    },
    {
        "key":"",
        "x":0,
        "y":0,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":0,
        "y":15,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":0,
        "y":30,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":0,
        "y":45,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":0,
        "y":60,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":0,
        "y":75,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":0,
        "y":90,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":70,
        "y":0,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":70,
        "y":15,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":70,
        "y":30,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":70,
        "y":45,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":70,
        "y":60,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":70,
        "y":75,
        "width":8,
        "height":15
    },
    {
        "key":"",
        "x":70,
        "y":90,
        "width":8,
        "height":15
    },
];

MOUSE_LAYOUT_WIDTH = 80;
MOUSE_LAYOUT_HEIGHT = 105;